services:
  app:
    build: .
    container_name: repair-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - repair_network

  db:
    image: postgres:15-alpine
    container_name: repair-db
    environment:
      - POSTGRES_DB=repair_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    networks:
      - repair_network

networks:
  repair_network:
    driver: bridge
